language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - jruby
  - rbx-2
  - ruby-head
  - jruby-head

jdk: oraclejdk8

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
