language: ruby

rvm:
#  - ruby-head-clang
#  - ruby-head
  - ruby-2.1.3
#  - ruby-2.0.0-p0
#  - ruby-1.9.3-p547
#  - rbx-2.2.7
#  - jruby-head
#  - jruby-1.7.11

#jdk: oraclejdk8

notifications:
  webhooks: https://xn--honsh-pfb.beskow.de/travis
